# Generated by Django 3.2.13 on 2022-05-05 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='razas',
            new_name='raza',
        ),
    ]
