# Generated by Django 3.2.13 on 2022-05-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_rename_razas_mascota_raza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='raza',
        ),
    ]
